name: Run Tests

on: [push]

jobs:
  build-with-inputs:
    runs-on: ubuntu-latest

    steps:
      - uses: brandoncorrea/clojure-base@master
        with:
          clojure-version: 1.11.1.1119
          java-version: 8
          java-distribution: 'zulu'

      - name: Execute Clojure
        run: clojure -e "(+ 1 2)"

  build-with-defaults:
    runs-on: ubuntu-latest

    steps:
      - uses: brandoncorrea/clojure-base@master
      - name: Execute Clojure
        run: clojure -e "(+ 1 2)"
